(define (problem p10-grounded)
(:domain vampire-grounded-for-p10)
(:objects
)
(:init
   (slayer-is-alive)
   (slayer-is-in-room1)
   (vampire-is-alive)
   (vampire-is-in-room8)
   (light-on-room1)
   (light-on-room2)
   (light-on-room3)
   (light-on-room4)
   (light-on-room5)
   (light-on-room6)
   (light-on-room7)
   (light-on-room8)
   (light-on-room9)
   (light-on-room10)
   (light-on-room11)
   (light-on-room12)
   (light-on-room13)
   (light-on-room14)
   (light-on-room15)
)
(:goal
    (and
        (slayer-is-alive)
        (not (vampire-is-alive))
    )
)
)
